In [49]:
import pandas as pd
import numpy as np

from sklearn.decomposition import TruncatedSVD

### STEP1. OTT별 영화 콘텐츠 가져오기

In [2]:
#OTT별 영화 콘텐츠 가져오기
neflix_contents = pd.read_excel(r"D:\Python\TM\TeamProject/netflix_contents.xlsx")
watch_contents = pd.read_excel(r"D:\Python\TM\TeamProject/watcha_contents.xlsx")
tiving_contents = pd.read_excel(r"D:\Python\TM\TeamProject/tiving_contents.xlsx")
disney_contents = pd.read_excel(r"D:\Python\TM\TeamProject/디즈니플러스.xlsx")

In [5]:
neflix_contents["OTT"] = "넷플릭스"
watch_contents["OTT"] = "왓챠"
tiving_contents["OTT"] = "티빙"
disney_contents["OTT"] = "디즈니"

In [25]:
disney_contents.loc[:,["TITLE","GENRES","OTT"]]

                    TITLE      GENRES  OTT
0                   만달로리안    스페이스 오페라  디즈니
1                  필사의 도전      역사 드라마  디즈니
2                    완다비전  슈퍼히어로, 시트콤  디즈니
3               팔콘과 윈터 솔져   슈퍼히어로, 액션  디즈니
4                      로키  슈퍼히어로, 판타지  디즈니
..                    ...         ...  ...
59              비하인드 어트랙션       다큐멘터리  디즈니
60               자라나는 동물들          자연  디즈니
61                스파크 스토리       다큐멘터리  디즈니
62                 우주 속으로       다큐멘터리  디즈니
63  The Beatles: Get Back       다큐멘터리  디즈니

[64 rows x 3 columns]

In [30]:
movie_contents  =pd.concat( [neflix_contents.loc[:,"TITLE":],watch_contents.loc[:,"TITLE":] ])
movie_contents  =pd.concat([movie_contents,tiving_contents.loc[:,"TITLE":] ])
movie_contents  =pd.concat([movie_contents,disney_contents.loc[:,"TITLE":] ])

In [539]:
movie_contents

,TITLE,LINK,GENRES,OTT
0,지옥,https://www.netflix.com/kr/title/81256675,TV 프로그램·미스터리 TV 프로그램·범죄 한국 드라마 TV 프로그램·스릴러 TV ...,넷플릭스
1,오징어 게임,https://www.netflix.com/kr/title/81040344,한국 드라마 TV 프로그램·스릴러 TV 드라마,넷플릭스
2,아케인,https://www.netflix.com/kr/title/81435684,TV 프로그램·판타지 미국 TV 프로그램 TV 프로그램·액션 & 어드벤처,넷플릭스
3,D.P.,https://www.netflix.com/kr/title/81280917,한국 드라마 TV 드라마,넷플릭스
4,마이 네임,https://www.netflix.com/kr/title/81011211,TV 프로그램·범죄 한국 드라마 TV 프로그램·스릴러 TV 프로그램·액션 & 어드벤처,넷플릭스
...,...,...,...,...
59,비하인드 어트랙션,NaN,다큐멘터리,디즈니
60,자라나는 동물들,NaN,자연,디즈니
61,스파크 스토리,NaN,다큐멘터리,디즈니
62,우주 속으로,NaN,다큐멘터리,디즈니
63,The Beatles: Get Back,NaN,다큐멘터리,디즈니

### OTT별 사용자 정보 가져오기

In [342]:
#OTT별 영화 콘텐츠 가져오기
neflix_rating = pd.read_excel(r"D:\Python\TM\TeamProject/netflix_rating.xlsx")
watch_rating = pd.read_excel(r"D:\Python\TM\TeamProject/watch_rating.xlsx")
tiving_rating = pd.read_excel(r"D:\Python\TM\TeamProject/tivig_rating.xlsx")
disney_ratings = pd.read_excel(r"D:\Python\TM\TeamProject/dinsey_rating.xlsx")

In [343]:
tiving_rating

,nickname,[무삭제판] 해피니스,러브캐처 인 서울,스트릿댄스 걸스 파이터,엄마는 아이돌,유 퀴즈 온 더 블럭,놀라운 토요일,싱어게인2,스트릿우먼파이터 ON THE STAGE,술꾼도시여자들,...,환승연애,라켓보이즈,2021 MAMA 노미네이션,어른연습생,러브캐처 2,국민영수증,여고추리반,[예고] 여고추리반2,슬기로운 의사생활 시즌2,신서유기 스페셜 스프링 캠프
0,sososky,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,내일의나,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,어썸,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,돈먹는하마,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,노바디,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236,연정,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
237,양구,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
238,예강파파,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
239,기이상,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
240,신투,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# Item-based Collaborative Filtering ( 아이템 기반 영화추천)

In [344]:
movie_rate=pd.concat( [neflix_rating,watch_rating ,tiving_rating,disney_ratings])

In [345]:
movie_rate=movie_rate.fillna(0)

In [346]:
movie_rate.columns.name="TITLE"

In [347]:
movie_rate=movie_rate.set_index("nickname")

In [348]:
movie_rate

TITLE,지옥,오징어 게임,아케인,D.P.,마이 네임,킹덤,브리저튼,스위트홈,무브 투 헤븐: 나는 유품정리사입니다,인간수업,...,제프 골드블럼의 호기심 세계,이매지니어링 스토리,마블의 영웅 프로젝트,디즈니의 평범한 하루 (단편),도전! 안내견,디즈니 인사이더,소품과 영화,디즈니 갤러리 / 스타워즈: 만달로리안,숨겨진 세상: 겨울왕국2 메이킹,별난 여행
nickname,,,,,,,,,,,,,,,,,,,,,
필름닷,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
씨네플레이,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
뀨우,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
구공탄,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
마시우,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ahendufrhd,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
찌니,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Jeongyaa,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
영이,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
yogafield,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [349]:
movie_user_rate = movie_rate.values.T
movie_user_rate.shape

(199, 1533)

In [350]:
SVD = TruncatedSVD(n_components=12, random_state=3)
matrix = SVD.fit_transform(movie_user_rate)
matrix.shape

(199, 12)

In [351]:
matrix

array([[ 4.84917549e-10,  1.00040024e+01, -5.58520916e-05, ...,
         1.07508637e-02, -1.04104179e+00,  5.20875432e-02],
       [-1.25786045e-10,  8.48760690e-02, -6.03258255e-07, ...,
         1.26456624e-03, -8.31799127e-02,  4.89052899e-03],
       [-3.90662314e-20, -1.16154848e-16,  2.22503551e-17, ...,
         4.09796451e-16, -9.35389053e-17,  1.02716959e-16],
       ...,
       [-0.00000000e+00,  0.00000000e+00, -0.00000000e+00, ...,
        -0.00000000e+00,  0.00000000e+00, -0.00000000e+00],
       [-0.00000000e+00,  0.00000000e+00, -0.00000000e+00, ...,
        -0.00000000e+00,  0.00000000e+00, -0.00000000e+00],
       [ 1.59403918e-01, -7.29864457e-06, -1.32349963e-02, ...,
         1.77835644e-03,  1.29214043e-03,  2.74046416e-03]])

In [352]:
corr = np.corrcoef(matrix)
corr[np.isnan(corr)]  = 0
corr

c:\users\user\appdata\local\programs\python\python38\lib\site-packages\numpy\lib\function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
c:\users\user\appdata\local\programs\python\python38\lib\site-packages\numpy\lib\function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]

array([[ 1.        ,  0.77458597, -0.04654436, ...,  0.        ,
         0.        , -0.03084057],
       [ 0.77458597,  1.        , -0.02348172, ...,  0.        ,
         0.        , -0.00369329],
       [-0.04654436, -0.02348172,  1.        , ...,  0.        ,
         0.        ,  0.27001409],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.03084057, -0.00369329,  0.27001409, ...,  0.        ,
         0.        ,  1.        ]])

In [404]:
movie_title = movie_rate.columns
movie_title_list=list(movie_rate.columns)

['지옥',
 '오징어 게임',
 '아케인',
 'D.P.',
 '마이 네임',
 '킹덤',
 '브리저튼',
 '스위트홈',
 '무브 투 헤븐: 나는 유품정리사입니다',
 '인간수업',
 '섹스/라이프',
 '에밀리, 파리에 가다',
 '종말의 발키리',
 '한마 바키',
 '퀸스 갬빗',
 '신세계로부터',
 '뤼팽',
 '카우보이 비밥',
 '비하인드 허 아이즈',
 '조용한 희망',
 '지니 & 조지아',
 '바바리안',
 '마이클 조던: 더 라스트 댄스',
 '러브, 데스 + 로봇',
 '스위트 투스: 사슴뿔을 가진 소년',
 '10대 사건으로 보는 제2차 세계대전',
 '빌어먹을 세상 따위',
 '에덴즈 제로',
 '보디가드',
 '메시아',
 '더 크루: 갱랜드',
 '어둠 속으로',
 '심야식당: 도쿄 스토리',
 '백스피릿',
 '네버 해브 아이 에버',
 '섀도우 앤 본',
 '라그나로크',
 '보건교사 안은영',
 '죽어도 선덜랜드',
 '애니멀',
 '아리스 인 보더랜드',
 '은밀한 회사원',
 '오스만 제국의 꿈',
 '미스트',
 '슈퍼크룩스',
 '맨헌트',
 '영 로열스',
 '트루 스토리',
 '페이트: 윙스의 전설',
 '알라와비 여고',
 '채플웨이트: 피의 저택',
 '도굴',
 '더듬이TV: 우당탕탕 안테나',
 '왕좌의 게임',
 '거침없이 하이킥',
 '팽',
 '귀멸의 칼날',
 '해리포터와 마법사의 돌',
 '해리포터와 비밀의 방',
 '해리포터와 아즈카반의 죄수',
 '해리포터와 불의 잔',
 '해리포터와 불사조 기사단',
 '해리포터와 혼혈왕자',
 '해리포터와 죽음의 성물 1',
 '해리포터와 죽음의 성물 2',
 '체르노빌',
 '하이큐!!',
 '무한도전',
 '와이 우먼 킬',
 '주술회전',
 '런닝맨',
 '스토브리그',
 '베놈',
 '덱스터',
 '태양의 후예',
 '새빛남고 학생회',
 '이누야샤',
 '진격의 거인',
 '커피 한잔 할까요?',
 '도쿄 리벤저스',
 '언내추럴',
 '어쩌다 발견한 하루',
 '리버풀 FC: 엔드 오브 스톰',
 '징크스',
 '킬링 이브',
 "2021 스페셜 토크쇼 'Let’s BTS'",
 '명탐정 코난',
 '전생했더니 슬라임이었던 건에 대하여',
 '신인왕 방탄소년단 - 채널방탄',
 '클라리스',
 '그린 나이트',
 '나는 SOLO',
 '30살까지 동정이면 마법사가 될 수 있대',
 '오피스',
 '극장판 귀멸의 칼날: 무한열차편',
 '다만 악에서 구하소서',
 '지붕 뚫고 하이킥',
 '원피스',
 '닥터스',
 '섹스 앤 더 시티',
 '[무삭제판] 해피니스',
 '러브캐처 인 서울',
 '스트릿댄스 걸스 파이터',
 '엄마는 아이돌',
 '유 퀴즈 온 더 블럭',
 '놀라운 토요일',
 '싱어게인2',
 '스트릿우먼파이터 ON THE STAGE',
 '술꾼도시여자들',
 '백수세끼',
 '바퀴 달린 집 3',
 '공작도시',
 '슬기로운 산촌생활',
 '멜랑꼴리아',
 '지리산',
 '금쪽같은 내새끼',
 '해방타운',
 '세리머니 클럽',
 '어사와 조이',
 '해피니스',
 '아는 형님',
 'JTBC 뉴스룸',
 '해치지 않아',
 '술꾼도시여자들 뒤풀이',
 '다수의 수다',
 '도시어부3',
 '돌싱글즈2',
 '내가 키운다',
 '뭉쳐야 찬다2',
 'Show Me The Money 10',
 '신비아파트 고스트볼Z: 어둠의 퇴마사',
 '스트릿 우먼 파이터',
 '맛있는 녀석들',
 '스트릿우먼파이터온더스테이지 비하인드',
 '키마이라',
 '풍류대장',
 '명탐정 코난 19기 (더빙)',
 '스트릿 우먼 파이터 갈라 토크쇼',
 '유미의 세포들',
 '환승연애',
 '라켓보이즈',
 '2021 MAMA 노미네이션',
 '어른연습생',
 '러브캐처 2',
 '국민영수증',
 '여고추리반',
 '[예고] 여고추리반2',
 '슬기로운 의사생활 시즌2',
 '신서유기 스페셜 스프링 캠프',
 '만달로리안',
 '\xa0필사의 도전',
 '완다비전',
 '팔콘과 윈터 솔져',
 '로키',
 '베네딕트 비밀클럽',
 '천재소녀 두기',
 '호크아이',
 '하이 스쿨 뮤지컬: 뮤지컬: 시리즈',
 '나의 대통령 일기',
 '마이티 덕: 게임 체인저',
 '빅샷',
 '터너와 후치',
 '저스트 비욘드',
 '디즈니 얽히고 엮인 그녀들',
 '재미있는 디즈니 공작교실',
 '앙코르! 다시 무대로',
 '픽사',
 '리얼 라이프, 픽사',
 '샵 클래스: 어린 공학자',
 '도전! 디즈니 셰프',
 '빅 핍: 누구의 거짓말?',
 '머펫 나우',
 '지구에서 네드에게',
 '로빈 로버츠: 세상을 토론하다',
 '런닝맨: 뛰는 놈 위에 노는 놈',
 '포키는 궁금한 게 많아요',
 '스파크쇼츠',
 '디즈니 애니메이션 스튜디오 단편 모음',
 '제니메이션',
 '미키마우스의 즐거운 세상',
 '픽사 팝콘',
 '스타워즈: 배드 배치',
 '몬스터 근무일지',
 '칩 앤 데일: 파크 라이프',
 'What If...?',
 '구피가 집에서 잘 지내는 방법',
 '더그의 일상',
 '스타워즈: 비전스',
 '올라프가 전해요',
 '제프 골드블럼의 호기심 세계',
 '이매지니어링 스토리',
 '마블의 영웅 프로젝트',
 '디즈니의 평범한 하루 (단편)',
 '도전! 안내견',
 '디즈니 인사이더',
 '소품과 영화',
 '디즈니 갤러리 / 스타워즈: 만달로리안',
 '숨겨진 세상: 겨울왕국2 메이킹',
 '별난 여행']

In [405]:
def get_recommend_movie_by_item(title) : 
    coffey_hands = movie_title_list.index(title)
    corr_coffey_hands=corr[coffey_hands]
    recomend_movie_list=list(movie_title[(corr_coffey_hands<1.0) & (corr_coffey_hands>0.9)])
    dict_movie ={}
    for x in recomend_movie_list :
        dict_movie[x] = movie_contents[movie_contents["TITLE"] == x].values[0][3]
    return dict_movie

In [474]:
get_recommend_movie_by_item("지옥")

{'지옥': '넷플릭스', '죽어도 선덜랜드': '넷플릭스', '애니멀': '넷플릭스'}

### 코사인유사도를 이용하여 영화 제목의 유사한 장르를 가진 영화 추천

In [88]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [356]:
def convert(x):
    i=''
    if  not isinstance(x,float) : 
        i = x.split(',')
    return ' '.join(i)

In [357]:
movie_contents['GENRES'] = movie_contents['GENRES'].apply(convert)

In [358]:
movie_contents

,TITLE,LINK,GENRES,OTT
0,지옥,https://www.netflix.com/kr/title/81256675,TV 프로그램·미스터리 TV 프로그램·범죄 한국 드라마 TV 프로그램·스릴러 TV ...,넷플릭스
1,오징어 게임,https://www.netflix.com/kr/title/81040344,한국 드라마 TV 프로그램·스릴러 TV 드라마,넷플릭스
2,아케인,https://www.netflix.com/kr/title/81435684,TV 프로그램·판타지 미국 TV 프로그램 TV 프로그램·액션 & 어드벤처,넷플릭스
3,D.P.,https://www.netflix.com/kr/title/81280917,한국 드라마 TV 드라마,넷플릭스
4,마이 네임,https://www.netflix.com/kr/title/81011211,TV 프로그램·범죄 한국 드라마 TV 프로그램·스릴러 TV 프로그램·액션 & 어드벤처,넷플릭스
...,...,...,...,...
59,비하인드 어트랙션,NaN,다큐멘터리,디즈니
60,자라나는 동물들,NaN,자연,디즈니
61,스파크 스토리,NaN,다큐멘터리,디즈니
62,우주 속으로,NaN,다큐멘터리,디즈니
63,The Beatles: Get Back,NaN,다큐멘터리,디즈니

In [359]:
transformer = CountVectorizer()
genres_vector = transformer.fit_transform(movie_contents['GENRES'])
genres_vector.shape

(364, 89)

In [360]:
similarity = cosine_similarity(genres_vector, genres_vector)
similarity

array([[1.        , 0.78258558, 0.83005736, ..., 0.        , 0.        ,
        0.        ],
       [0.78258558, 1.        , 0.57854191, ..., 0.        , 0.        ,
        0.        ],
       [0.83005736, 0.57854191, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 1.        ,
        1.        ],
       [0.        , 0.        , 0.        , ..., 1.        , 1.        ,
        1.        ],
       [0.        , 0.        , 0.        , ..., 1.        , 1.        ,
        1.        ]])

In [361]:
similarity = similarity.argsort()
similarity

array([[181, 259, 258, ...,  57,  28,   0],
       [181, 259, 258, ...,   9,   7,   1],
       [363, 150, 249, ...,  61,  66,   2],
       ...,
       [  0, 237, 236, ..., 340, 353, 363],
       [  0, 237, 236, ..., 340, 353, 363],
       [  0, 237, 236, ..., 340, 353, 363]], dtype=int64)

In [362]:
similarity = similarity[:, ::-1]
similarity

array([[  0,  28,  57, ..., 258, 259, 181],
       [  1,   7,   9, ..., 258, 259, 181],
       [  2,  66,  61, ..., 249, 150, 363],
       ...,
       [363, 353, 340, ..., 236, 237,   0],
       [363, 353, 340, ..., 236, 237,   0],
       [363, 353, 340, ..., 236, 237,   0]], dtype=int64)

In [537]:
def get_recommend_movie_list_genre( movie_genre,top=50):
    
    search_df = movie_contents[movie_contents['GENRES'] == movie_genre ]
    search_df_index = search_df.index.values
    similarity_index = similarity[search_df_index, :top].reshape(-1)
    similarity_index = similarity_index[similarity_index != search_df_index] #제목이 movie_title 인 영화 제외
   
    result = movie_contents.iloc [similarity_index]
    
    result = result[:2]
    movie_dict ={}
    for idx, row in result.iterrows():        
        movie_dict[row["TITLE"]] =  row["OTT"]
    
    
    return movie_dict

In [533]:
def get_recommend_movie_list_title( genre, ott,top=50):
    
    search_df = movie_contents[movie_contents['TITLE'] == genre]
    search_df_index = search_df.index.values
    similarity_index = similarity[search_df_index, :top].reshape(-1)
    similarity_index = similarity_index[similarity_index != search_df_index] #제목이 movie_title 인 영화 제외
   
    result = movie_contents.iloc [similarity_index]

    if  ott in list( result["OTT"]) :
        result = result[result["OTT"] == ott ] 
    
    result = result[:2]
    movie_dict ={}
    for idx, row in result.iterrows():        
        movie_dict[row["TITLE"]] =  row["OTT"]
    
    
    return movie_dict

In [464]:
get_recommend_movie_list_title(movie_title='마이 네임',ott="왓챠")

{'더 크루: 갱랜드': '넷플릭스', '뤼팽': '넷플릭스'}

,TITLE,LINK,GENRES,OTT
30,더 크루: 갱랜드,https://www.netflix.com/kr/title/81175433,TV 프로그램·범죄 TV 프로그램·스릴러 TV 프로그램·액션 & 어드벤처,넷플릭스
16,뤼팽,https://www.netflix.com/kr/title/80994082,TV 프로그램·미스터리 TV 프로그램·범죄 도서 원작 TV 프로그램 TV 프로그램·...,넷플릭스

## 사용자 응답에 대한 결과 확인

In [648]:
ott_suvery =pd.read_excel(r"D:\Python\TM\TeamProject/ott_survey.xlsx")

In [649]:
ott_suvery=ott_suvery.drop(['Unnamed: 0','index'],axis=1)

In [650]:
ott_suvery

,USER_ID,넷플릭스,왓챠,티빙,디즈니,OTT_LIST,사용유무,OTT플랫폼,프로그램유형,시청목록,선호콘텐츠,선호장르,요금,최소요금
0,user_01,6,5,2,2,['넷플릭스'],사용중,"넷플릭스, 왓챠","드라마, 영화",넷플릭스 지옥이요.,"지옥, 로키","스릴러, 코미디, 미스터리","9,000원 ~ 11,000원 미만",9000
1,user_02,5,5,7,0,['티빙'],사용중,"넷플릭스, 티빙, seezn","실시간 시청 서비스 이용, 예능, 드라마",술꾼도시여자들,"무한도전, 스트릿 우먼 파이터, 놀라운 토요일","코미디, 예능","5,000원 ~7,000원 미만",5000
2,user_03,5,3,3,5,"['넷플릭스', '디즈니']",사용중,"넷플릭스, 티빙, 디즈니, 웨이브, 쿠팡플레이","드라마, 영화, 실시간 시청 서비스 이용",디즈니플러스,"로키, 호크아이, 완다비전","코미디, 히어로","5,000원 ~7,000원 미만",5000
3,user_04,4,2,3,6,['디즈니'],사용중,"넷플릭스, 티빙, 디즈니, 쿠팡플레이",영화,해피니스,"해피니스, 로키, 호크아이, 완다비전","판타지, 액션, 히어로","9,000원 ~ 11,000원 미만",9000
4,user_05,8,6,2,3,['넷플릭스'],사용중,"넷플릭스, 왓챠, 쿠팡플레이","실시간 시청 서비스 이용, 애니메이션, 영화, 드라마","전생슬, 던만추","체르노빌, 원피스, 오징어 게임, 지옥, 스위트홈","판타지, 액션, 애니메이션, 히어로","5,000원 미만",5000
5,user_06,3,1,3,1,"['넷플릭스', '티빙']",사용중,넷플릭스,드라마,굿닥터,지리산,다큐,"5,000원 ~7,000원 미만",5000
6,user_07,3,2,2,1,['넷플릭스'],사용중,넷플릭스,영화,"터닝포인트 911,그리고 테러와의 전쟁",킹덤,예능,"9,000원 ~ 11,000원 미만",9000
7,user_08,3,3,3,0,"['넷플릭스', '왓챠', '티빙']",사용중,넷플릭스,예능,맛있는 녀석들,오징어 게임,예능,"7,000원 ~ 9,000원 미만",7000
8,user_09,8,8,4,2,"['넷플릭스', '왓챠']",사용중,"넷플릭스, 티빙, 디즈니","영화, 예능, 드라마",슬기로운의사생활2,"무한도전, 아는 형님, 픽사","스릴러, 코미디, 액션, 미스터리, 예능","11,000원~ 13,000원 미만",11000
9,user_10,2,3,2,2,['왓챠'],사용중,왓챠,애니메이션,극주부도,픽사 팝콘,"코미디, 애니메이션, 예능","5,000원 미만",5000
10,user_11,4,4,7,0,['티빙'],사용중,"넷플릭스, 티빙, 웨이브","드라마, 예능",스트릿우먼파이터,"스트릿 우먼 파이터, 아는 형님, 오징어 게임","로맨스, 예능","5,000원 미만",5000
11,user_12,3,5,5,5,"['왓챠', '티빙', '디즈니']",사용중,티빙,"예능, 애니메이션, 다큐",술꾼도시여자들,"원피스, 아는 형님, 놀라운 토요일","판타지, 코미디, 다큐, 애니메이션, 예능","9,000원 ~ 11,000원 미만",9000
12,user_13,3,2,2,0,['넷플릭스'],사용중,넷플릭스,영화,오징어게임,없음,로맨스,"5,000원 ~7,000원 미만",5000
13,user_14,6,5,7,0,['티빙'],사용중,"넷플릭스, 티빙, 웨이브","예능, 실시간 시청 서비스 이용, 드라마",놀면뭐하니,스트릿 우먼 파이터,"로맨스, 코미디, 액션, 예능","5,000원 ~7,000원 미만",5000
14,user_15,6,5,6,4,"['넷플릭스', '티빙']",사용중,"넷플릭스, 티빙, 디즈니, 웨이브","예능, 영화, 드라마",술꾼도시여자들,"지옥, 로키, 완다비전","로맨스, 액션, 예능","9,000원 ~ 11,000원 미만",9000
15,user_16,5,6,2,3,['왓챠'],사용중,"넷플릭스, 쿠팡플레이","애니메이션, 영화",그 해 우리는,"체르노빌, 원피스, 로키","로맨스, 판타지, 코미디, 애니메이션","5,000원 ~7,000원 미만",5000
16,user_17,4,4,3,3,"['넷플릭스', '왓챠']",사용중,디즈니,"영화, 예능",어벤저스 엔드게임,호크아이,"액션, 히어로, 예능","7,000원 ~ 9,000원 미만",7000
17,user_18,6,6,3,0,"['넷플릭스', '왓챠']",사용중,"넷플릭스, 쿠팡플레이","영화, 드라마",재밌게는 아니지만...오징어게임,체르노빌,"로맨스, 판타지, 스릴러, 미스터리","5,000원 ~7,000원 미만",5000
18,user_19,6,7,3,1,['왓챠'],사용중,넷플릭스,"드라마, 영화",지옥,"체르노빌, 오피스, 픽사","로맨스, 코미디, 액션","7,000원 ~ 9,000원 미만",7000
19,user_20,7,8,6,4,['왓챠'],사용중,"넷플릭스, 티빙","드라마, 영화, 애니메이션",술꾼도시여자들,"무한도전, 스트릿 우먼 파이터, 로키","로맨스, 판타지, 코미디, 액션, 애니메이션, 히어로, 예능","7,000원 ~ 9,000원 미만",7000
20,user_21,8,7,4,1,['넷플릭스'],사용중,"넷플릭스, 왓챠, 디즈니","드라마, 영화, 예능",지옥,"무한도전, 스트릿 우먼 파이터","스릴러, 코미디, 액션","7,000원 ~ 9,000원 미만",7000
21,user_22,4,3,5,0,['티빙'],사용중,"넷플릭스, 티빙","드라마, 예능",돌싱글즈,없음,예능,"5,000원 미만",5000
22,user_23,7,5,4,2,['넷플릭스'],사용중,넷플릭스,"드라마, 예능, 영화",마이네임,"지옥, 픽사","로맨스, 코미디, 애니메이션","5,000원 ~7,000원 미만",5000
23,user_24,9,9,6,2,"['넷플릭스', '왓챠']",사용중,"넷플릭스, 왓챠, 티빙, 쿠팡플레이","예능, 애니메이션, 실시간 시청 서비스 이용, 드라마, 영화",해피니스,없음,"로맨스, 판타지, 스릴러, 코미디, 액션, 미스터리, 애니메이션, 예능","5,000원 ~7,000원 미만",5000

In [646]:
def merge_two_dicts(x, y):
 
    z = x.copy()
    
    z.update(y)
    
    return z

In [689]:
user_movie=[]
for idx, row in ott_suvery.iterrows():
    pre_title  = row["선호콘텐츠"].split(',')
    
    pre_dict_all ={}
    for title in pre_title :
        ott_list = row["OTT_LIST"].replace('[','').replace(']','').split(',')
        
        if title != "없음" :
            pre_dict = get_recommend_movie_by_item(title.strip())
           
            for ott in ott_list :
                pre_dict1 = get_recommend_movie_list_title(title,ott)
                if(bool(pre_dict1)) :
                    pre_dict = merge_two_dicts(pre_dict,pre_dict1)
            pre_dict_all = merge_two_dicts(pre_dict_all,pre_dict )
                
    user_movie.append(pre_dict_all)

In [690]:
user_movie

[{'지옥': '넷플릭스',
  '죽어도 선덜랜드': '넷플릭스',
  '애니멀': '넷플릭스',
  '보디가드': '넷플릭스',
  '클릭베이트': '넷플릭스',
  '머펫 나우': '디즈니',
  '디즈니 애니메이션 스튜디오 단편 모음': '디즈니',
  '별난 여행': '디즈니'},
 {'런닝맨': '왓챠',
  '명탐정 코난': '왓챠',
  '주피터스 레거시': '넷플릭스',
  '오행자객': '넷플릭스',
  '스트릿댄스 걸스 파이터': '티빙',
  '해치지 않아': '티빙',
  '스트릿 우먼 파이터 갈라 토크쇼': '티빙',
  '세리머니 클럽': '티빙',
  '아는 형님': '티빙'},
 {'머펫 나우': '디즈니',
  '디즈니 애니메이션 스튜디오 단편 모음': '디즈니',
  '별난 여행': '디즈니',
  '더 크루: 갱랜드': '넷플릭스',
  '뤼팽': '넷플릭스',
  '완다비전': '디즈니'},
 {'지리산': '티빙',
  '키마이라': '티빙',
  '에밀리, 파리에 가다': '넷플릭스',
  '네버 해브 아이 에버': '넷플릭스',
  '머펫 나우': '디즈니',
  '디즈니 애니메이션 스튜디오 단편 모음': '디즈니',
  '별난 여행': '디즈니',
  '완다비전': '디즈니'},
 {'덱스터': '왓챠',
  '죽어도 선덜랜드': '넷플릭스',
  '사랑의 진실게임': '넷플릭스',
  '이누야샤': '왓챠',
  '원피스': '왓챠',
  '미스트': '넷플릭스',
  '지옥': '넷플릭스',
  '애니멀': '넷플릭스',
  '스위트홈': '넷플릭스'},
 {'해피니스': '티빙', '키마이라': '티빙', '조용한 희망': '넷플릭스', '미스트': '넷플릭스'},
 {'킹덤': '넷플릭스', '스위트홈': '넷플릭스', '마이 네임': '넷플릭스'},
 {'미스트': '넷플릭스', '스위트홈': '넷플릭스', '인간수업': '넷플릭스'},
 {'런닝맨': '왓챠',
  '명탐정 코난': '왓챠',
  '주피터스 레거시': '넷플릭스',
  '오행자객': '넷플릭스',
  '놀라운 토요일': '티빙',
  '세리머니 클럽': '티빙',
  '저스트 비욘드': '디즈니',
  '픽사 팝콘': '디즈니'},
 {'픽사': '디즈니', '비하인드 허 아이즈': '넷플릭스', '래치드': '넷플릭스'},
 {'스트릿댄스 걸스 파이터': '티빙',
  '해치지 않아': '티빙',
  '스트릿 우먼 파이터 갈라 토크쇼': '티빙',
  '위험한 불장난': '넷플릭스',
  '영 로열스': '넷플릭스',
  '놀라운 토요일': '티빙',
  '세리머니 클럽': '티빙',
  '미스트': '넷플릭스'},
 {'이누야샤': '왓챠',
  '원피스': '왓챠',
  '클릭베이트': '넷플릭스',
  '맨헌트': '넷플릭스',
  '놀라운 토요일': '티빙',
  '세리머니 클럽': '티빙',
  '아는 형님': '티빙'},
 {},
 {'스트릿댄스 걸스 파이터': '티빙',
  '해치지 않아': '티빙',
  '스트릿 우먼 파이터 갈라 토크쇼': '티빙',
  '위험한 불장난': '넷플릭스',
  '영 로열스': '넷플릭스'},
 {'지옥': '넷플릭스',
  '죽어도 선덜랜드': '넷플릭스',
  '애니멀': '넷플릭스',
  '보디가드': '넷플릭스',
  '클릭베이트': '넷플릭스',
  '머펫 나우': '디즈니',
  '디즈니 애니메이션 스튜디오 단편 모음': '디즈니',
  '별난 여행': '디즈니',
  '완다비전': '디즈니'},
 {'덱스터': '왓챠',
  '죽어도 선덜랜드': '넷플릭스',
  '사랑의 진실게임': '넷플릭스',
  '이누야샤': '왓챠',
  '원피스': '왓챠',
  '머펫 나우': '디즈니',
  '디즈니 애니메이션 스튜디오 단편 모음': '디즈니',
  '별난 여행': '디즈니'},
 {'킹덤': '넷플릭스', '인간수업': '넷플릭스'},
 {'덱스터': '왓챠', '죽어도 선덜랜드': '넷플릭스', '사랑의 진실게임': '넷플릭스'},
 {'덱스터': '왓챠',
  '죽어도 선덜랜드': '넷플릭스',
  '사랑의 진실게임': '넷플릭스',
  '저스트 비욘드': '디즈니',
  '픽사 팝콘': '디즈니'},
 {'런닝맨': '왓챠',
  '명탐정 코난': '왓챠',
  '주피터스 레거시': '넷플릭스',
  '오행자객': '넷플릭스',
  '스트릿댄스 걸스 파이터': '티빙',
  '해치지 않아': '티빙',
  '스트릿 우먼 파이터 갈라 토크쇼': '티빙',
  '머펫 나우': '디즈니',
  '디즈니 애니메이션 스튜디오 단편 모음': '디즈니',
  '별난 여행': '디즈니'},
 {'런닝맨': '왓챠',
  '명탐정 코난': '왓챠',
  '주피터스 레거시': '넷플릭스',
  '오행자객': '넷플릭스',
  '스트릿댄스 걸스 파이터': '티빙',
  '해치지 않아': '티빙',
  '스트릿 우먼 파이터 갈라 토크쇼': '티빙'},
 {},
 {'지옥': '넷플릭스',
  '죽어도 선덜랜드': '넷플릭스',
  '애니멀': '넷플릭스',
  '보디가드': '넷플릭스',
  '클릭베이트': '넷플릭스',
  '저스트 비욘드': '디즈니',
  '픽사 팝콘': '디즈니'},
 {}]

In [691]:
#OTT 플랫폼에 해당하는 대표 프로그램 정보 가져오기
def getOTTMainProgram(ott_list) :
    ott_preference = pd.read_excel(r"D:\Python\TM\TeamProject/OTT프로그램정리.xlsx")
    
    main_programs = {}

    for i in ott_list :
        
        ott_movies = ott_preference[ott_preference["OTT프로그램"]== i.strip()].values[0][4]
        for x in ott_movies.split(','):
            main_programs[x.strip()] = i.strip()
            
    return main_programs

In [692]:
for idx, row in ott_suvery.iterrows(): 
    ## 선호콘텐츠가 없는 경우 OTT_LIST의 대표 프로그램을 세팅
    if bool(user_movie[idx]) ==False :

        ott = row["OTT_LIST"]
        ott = ott.replace('\'','')
        ott = ott.replace('[','')
        ott = ott.replace(']','')
        ott_list = ott.split(',')
        
        dict_movie=getOTTMainProgram(ott_list)
        user_movie[idx].update(dict_movie)

In [709]:
user_recomend={}
for idx, row in ott_suvery.iterrows(): 
    ott = row["OTT_LIST"]
    ott = ott.replace('\'','')
    ott = ott.replace('[','')
    ott = ott.replace(']','')
    ott_list = ott.split(',')
    user_recomend[row["USER_ID"]] = [ ott_list ,user_movie[idx]]

In [716]:
user_recomend["user_01"]

[['넷플릭스'],
 {'지옥': '넷플릭스',
  '죽어도 선덜랜드': '넷플릭스',
  '애니멀': '넷플릭스',
  '보디가드': '넷플릭스',
  '클릭베이트': '넷플릭스',
  '머펫 나우': '디즈니',
  '디즈니 애니메이션 스튜디오 단편 모음': '디즈니',
  '별난 여행': '디즈니'}]

### 최종결과에 대한 txt파일로 저장

In [721]:
with open(r'D:\Python\TM\TeamProject/OTT설문조사결과.txt','w',encoding='UTF-8') as f :
    for k, v in user_recomend.items() :
        f.write(f'{k} : {v}\n')